#!/bin/sh

set -e
[ ! -f Gemfile ] || git diff --exit-code --cached -- Gemfile >/dev/null || bundle check

FILES_PATTERN='\.(js|coffee)(\..+)?$'
FORBIDDEN='console.log'

git diff --cached --name-only | grep -E $FILES_PATTERN | GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n $FORBIDDEN && echo 'COMMIT REJECTED Found "console.log" references in your javascript. Please remove them before commiting';

# my zsh does annoying things with !
[ $? -ne 0 ]
exec "$(git --exec-path)/../../share/git-core/templates/hooks/pre-commit.sample"
